source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StringExtensionHTML_Example', :exclusive => true do
  pod 'StringExtensionHTML', :path => '../'
end

target 'StringExtensionHTML_Tests', :exclusive => true do
  pod 'StringExtensionHTML', :path => '../'

  
end
