source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StringExtensionHTML_Example' do
  pod 'StringExtensionHTML', :path => '../'
end

target 'StringExtensionHTML_Tests' do
  pod 'StringExtensionHTML', :path => '../'

  
end
